name: "Automatic Releases with SHA Hashes"
author: "marvinpinto and plu5"
description: "Automate the GitHub release process"
inputs:
  repo_token:
    description: "GitHub secret token"
    required: true
  automatic_release_tag:
    description: "Git tag (for automatic releases)"
    required: false
  is_tag_static:
    description: "Generate changelog from the same tag instead of previous"
    required: false
    default: false
  tag_annotation:
    description: "Optional tag annotation"
    required: false
  draft:
    description: "Should this release be marked as a draft?"
    required: false
    default: false
  prerelease:
    description: "Should this release be marked as a pre-release?"
    required: false
    default: true
  title:
    description: "Release title (for automatic releases)"
    required: false
  files:
    description: "Assets to upload to the release"
    required: false
outputs:
  automatic_releases_tag:
    description: "The release tag this action just processed"
  upload_url:
    description: "The URL for uploading additional assets to the release"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "briefcase"
  color: "red"
