name: Release new version

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
      annotation:
        type: string
        required: false
  push:
    paths: ['package.json'] # VERSION_FILE

env:
  VERSION_FILE: 'package.json'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2 # for the diff

      - if: inputs.version == ''
        name: Check whether version changed
        run: |
          DIFF=$(git diff -U0 HEAD^ HEAD $VERSION_FILE | grep '"version"')
          [ -n "$DIFF" ] && VERSION_CHANGED=true || VERSION_CHANGED=false
          echo "VERSION_CHANGED=$VERSION_CHANGED" >> $GITHUB_ENV

      - if: inputs.version != '' || env.VERSION_CHANGED == 'true'
        name: Get version and annotation
        run: |
          VERSION="${{ inputs.version }}"; ANNOTATION="${{ inputs.annotation }}"
          if [ -n $VERSION ]; then
            echo "ANNOTATION=$ANNOTATION" >> $GITHUB_ENV
          else
            VERSION=`echo $(jq -r '.version' $VERSION_FILE)`
            echo "${{ github.event.head_commit.message }}" > commit_msg
            ANNOTATION=$(tail -n +3 commit_msg)
            echo -e "ANNOTATION<<EOF\n$ANNOTATION\nEOF" >> $GITHUB_ENV
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - if: env.VERSION != ''
        uses: plu5/automatic-releases-with-sha-action@main
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: v${{ env.VERSION }}
          tag_annotation: ${{ env.ANNOTATION }}
          prerelease: false
